---
- name: Configure host.
  hosts: localhost
  roles: 
  - homebrew
  - python
  - npm
  # - macos

  # tasks:
  #   # # 4. Copy dotfiles from backup (Assumes dotfiles are in a repo)
  #   # - name: Clone dotfiles repository
  #   #   git:
  #   #     repo: 'git@github.com:yourusername/dotfiles.git'
  #   #     dest: '{{ ansible_env.HOME }}/dotfiles'
  #   #     version: master

  #   # - name: Symlink dotfiles
  #   #   file:
  #   #     src: "{{ item.src }}"
  #   #     dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
  #   #     state: link
  #   #     force: yes
  #   #   loop:
  #   #     - { src: "~/dotfiles/.zshrc", dest: ".zshrc" }
  #   #     - { src: "~/dotfiles/.gitconfig", dest: ".gitconfig" }

  #   # 5. Set macOS system preferences (example for Dock)
  #   - name: Set Dock size
  #     command: defaults write com.apple.dock tilesize -int 25
  #     notify:
  #       - Restart Dock


  # handlers:
  #   - name: Restart Dock
  #     command: killall Dock