---
# - name: Install pipx python package
#   ansible.builtin.pip:
#     name: pipx
#     state: present
- name: change shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh)

- name: Install multiple packages from list
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    # global: yes
  with_items: "{{ pip_packages }}"
