---
- name: Install pipx python package
  ansible.builtin.pip:
    name: pipx
    state: present

- name: Install multiple packages from list
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    global: yes
  with_items: "{{ pip_packages }}"