---
- name: check python is coming from pyenv
  command: which python
  register: output
  changed_when: false
  # failed_when: '"homebrew" in output.msg'
  # TODO: work on this later https://stackoverflow.com/questions/75308705/changed-when-in-ansible

- debug: msg="{{ output.stdout }}"

- name: Install multiple packages from list
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pip_packages }}"